name: Build Driver

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Install Windows Driver Kit
      run: |
        choco install -y windows-driver-kit

    - name: Build Driver and App
      run: |
        msbuild ./WinEPPFilter-KMDF-Driver-Project/WinEPPFilter.sln /p:Configuration=Release /p:Platform=x64
